CREATE TABLE PROFESSORS(
	NOM VARCHAR(20),
	COGNOMS VARCHAR(30),
	EDAT INTEGER,
	ASSIGNATURA VARCHAR(20)
);

INSERT INTO PROFESSORS
VALUES('EDUARD','GUTIERREZ',35,'POSTGRES');

INSERT INTO PROFESSORS
VALUES('TONI','PIFARRE',40,'JAVA');

INSERT INTO PROFESSORS
VALUES('TITO','ERITJA',40,'JSP');

INSERT INTO PROFESSORS
VALUES('EDUARD','GUTIERREZ',35,'JS');